site_name: TouDoum-Framework
site_url: https://toudoum-framework.github.io
site_author: Gabin Lanore
site_description: >-
  A project for massively distribute tasks by writing a simple module and running it with cli

repo_name: TouDoum-Framework
repo_url: https://github.com/TouDoum-Framework/TouDoum-Framework
edit_uri: https://github.com/TouDoum-Framework/toudoum-framework.github.io

nav:
  - Home: index.md
  - Run:
    - Introduction: run/index.md
    - Requirement: run/requirement.md
    - Install: run/install.md
    - Upgrade: run/upgrade.md
  - Extend:
    - Introduction: extend/index.md
    - Create module: extend/create_module.md
    - Api: extend/api.md
    - Tasks: extend/tasks.md
    - Cli: extend/cli.md
  - Cli:
    - Introduction: cli/index.md
    - Install: cli/install.md
  - WebUI: webui.md
  - About: about.md

plugins:
  - minify:
      minify_html: true

extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/NetbytesSpace
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/netbytes-space/
    - icon: fontawesome/brands/github
      link: https://github.com/NetBytes-Space

theme:
  
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  
  icon:
    logo: logo
    repo: fontawesome/brands/git-alt
  
  font:
    text: Roboto

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top

  plugins:
    - social

  palette:
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
