site_name: TouDoum-Framework

repo_url: https://github.com/TouDoum-Framework/TouDoum-Framework

nav:
  - Home: index.md
  - About: about.md

extra:
  generator: true
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/NetbytesSpace
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/netbytes-space/
    - icon: fontawesome/brands/github
      link: https://github.com/NetBytes-Space

theme:
  
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/logo.png
  
  icon:
    logo: logo
    repo: fontawesome/brands/git-alt
  
  font:
    text: Roboto

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top

  plugins:
    - social

  palette:
  
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
